如果之前配置过logging，会根据具体情况保存到日志文件内。

```python
import sys
import logging


def callback_func(exc_type, exc_value, exc_traceback):
    logging.error("callback_func>>>>>>>>>>>>>>", exc_info=(
        exc_type, exc_value, exc_traceback))


sys.excepthook = callback_func
1 / 0

```

```
# 输出
ERROR:root:callback_func>>>>>>>>>>>>>>
Traceback (most recent call last):
  File "C:/Users/dong/PycharmProjects/err-callback-py/main.py", line 14, in <module>
    1 / 0
ZeroDivisionError: division by zero
```

